DOCS =									\
		install							\
		windows							\
		events							\
		syntax							\
		control							\
		hash							\
		http/request_processing					\
		http/server_names					\
		http/configuring_https_servers				\
		debugging_log						\
		http/converting_rewrite_rules				\
		howto_build_on_win32					\
		contributing_changes					\
		beginners_guide						\
		configure						\

TOP =									\
		download						\
		support							\
		linux_packages						\
