DOCS =									\
		faq							\
		install							\
		windows							\
		events							\
		syntax							\
		control							\
		hash							\
		http/request_processing					\
		http/server_names					\
		http/configuring_https_servers				\
		debugging_log						\
		beginners_guide						\

TOP =									\
		download						\
