name: Deploy nginx.org

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      deployment_env:
        type: choice
        description: Deployment environment
        options:
          - staging
          - prod
        default: staging

permissions:
  contents: read
  id-token: write


jobs:
  deploy:
    name: Deploy nginx.org
    uses: nginxinc/docs-actions/.github/workflows/nginx.org-make-aws.yml@87da99295dcb424d92efb2f6d783cc02e7c8da43 #v1.0.15
    with:
      deployment_env: ${{ github.event_name == 'workflow_dispatch' && inputs.deployment_env || 'staging' }}
    secrets:
      AZURE_VAULT_CLIENT_ID: ${{ secrets.AZURE_VAULT_CLIENT_ID }}
      AZURE_VAULT_SUBSCRIPTION_ID: ${{ secrets.AZURE_VAULT_SUBSCRIPTION_ID }}
      AZURE_VAULT_TENANT_ID: ${{ secrets.AZURE_VAULT_TENANT_ID }}
      DOCS_VAULTNAME: ${{ secrets.DOCS_VAULTNAME }}
      
    if: >-
      github.repository == 'nginx/nginx.org' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          (
            inputs.deployment_env == 'staging' ||
            (
              inputs.deployment_env == 'prod' &&
              github.ref == 'refs/heads/main'
            )
          )
        )
      )
