name: Deploy nginx.org

on:
  push:
    branches:
      - "**"
  workflow_dispatch:
    inputs:
      deployment_env:
        type: choice
        description: Deployment environment
        options:
          - staging
          - prod
        default: staging

permissions:
  contents: read
  id-token: write


jobs:
  deploy:
    name: Deploy nginx.org
    uses: nginxinc/docs-actions/.github/workflows/nginx.org-make-aws.yml@main
    with:
      deployment_env: ${{ github.event_name == 'workflow_dispatch' && inputs.deployment_env || 'staging' }}
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
      ALLOWED_USERS: ${{ secrets.ALLOWED_USERS }}
